language: php
 
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

os:
  - linux
  - osx

matrix:
  include:
    - os: osx
      language: generic
      install:
        # Updating PHP to 5.6.x
        - curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6
        - export PATH=/usr/local/php5/bin:$PATH
    - os: osx
      osx_image: xcode7.3
      language: generic
      env:
        - ATOM_CHANNEL=beta
      install:
        # Updating PHP to 7.0.x
        - curl -s http://php-osx.liip.ch/install.sh | bash -s 7.0
        - export PATH=/usr/local/php5/bin:$PATH

after_failure:
  - php --syntax-check --define display_errors=On --define log_errors=Off ./spec/files/good.php
  - php --syntax-check --define display_errors=On --define log_errors=Off ./spec/files/bad.php
 
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
script: phpunit
